// Auto-generated by the event gallery pipeline. Do not edit manually.
export interface EventGalleryImage {
  order: number;
  alt: string;
  width: number;
  height: number;
  src: string;
  srcSet: { webp: string; avif: string };
  sizes: string;
}

export interface EventGallery {
  fingerprint: string;
  images: EventGalleryImage[];
}

export const EVENT_GALLERIES: Record<string, EventGallery> = {};
